// src/components/ClubCard.tsx
import { Link } from 'react-router-dom';

const ClubCard = ({
  id,
  name,
  type,
  extraText,
  tour,
}: {
  id: string;
  name: string;
  type: string;
  extraText?: string;
  tour: string;
}) => {
  const clubLogo = `/golf-launch-monitor-averages/img/${type}.png`;

  return (
    <div className="club-option border border-white rounded-xl gap-3 p-2 my-4 text-center w-full font-bold">
      <Link
        to={`/golf-launch-monitor-averages/${tour}/${id}`}
        className="flex flex-col justify-center gap-2"
      >
        <div className="club-option-text">
          <h2 className="text-xl">{name}</h2>
          {extraText && <p className="text-xs">{extraText}</p>}
        </div>
        <div className="club-option-logo flex justify-center items-center">
          <img
            className="club-option-logo-image"
            src={clubLogo}
            alt={`${type} icon`}
          />
        </div>
      </Link>
    </div>
  );
};

export default ClubCard;

// components/ClubCard.vue
<template>
  <div class="club-option border border-white rounded-xl p-2 my-4 justify-items-center justify-center w-full">
    <NuxtLink :to="`/${$route.params.tour}/${id}`">
      <div class="club-option__text h-11">
        <h2>{{ name }}</h2>
        <p class="text-xs" v-if="extraText">{{ extraText }}</p>
      </div>
      <div class="club-option__logo flex justify-center">
        <img :src="clubLogo" :alt="`${type} icon`" />
      </div>
    </NuxtLink>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'

export default defineComponent({
  props: {
    id: {
      type: String,
      required: true,
    },
    name: {
      type: String,
      required: true,
    },
    type: {
      type: String,
      required: true,
    },
    extraText: {
      type: String,
      required: false,
    }
  },
  computed: {
    clubLogo() {
      return `/golf-launch-monitor-averages/img/${this.type}.png`;
    },
  },
})
</script>

<style scoped>
.club-option {
  height: 150px;
  width: 150px;
}
img {
  height: 80px;
  width: 80px;
}
</style>
