// components/StatsCard.vue
<template>
  <div class="stats-card border border-white m-4 p-2 rounded-xl justify-center justify-items-center align-middle items-center h-full">
    <div class="stats-card__name">
      <h3 class="text-large">{{ name }}</h3>
      <p v-if="extraInfo" class="text-sm">({{ extraInfo }})</p>
    </div>
    <h1 class="text-white text-4xl lg:text-5xl xl:text-6xl xl:7xl">{{ value }}</h1>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'

export default defineComponent({
  props: {
    name: {
      type: String,
      required: true,
    },
    extraInfo: {
      type: String,
      required: false
    },
    value: {
      type: String,
      required: true,
    },
  }
})
</script>

<style scoped>
.stats-card {
  height: 150px;

  &__name {
    height: 65px;
  }
}
</style>

// src/components/StatsCard.tsx
interface IStatsProps {
  name: string;
  extraInfo?: string;
  value: number;
}

const StatsCard = ({ name, extraInfo, value }: IStatsProps) => {
  return (
    <div className="stats-card border border-white m-4 p-2 rounded-xl justify-center justify-items-center align-middle items-center h-full gap-4 flex-col">
      <div className="stats-card-name">
        <h3 className="text-xl font-bold">{name}</h3>
        {extraInfo && <p className="text-sm italic">{extraInfo}</p>}
      </div>
      <h1 className="text-white text-4xl lg:text-5xl xl:text-6xl xl:7xl">
        {value}
      </h1>
    </div>
  );
};

export default StatsCard;
