// components/TourCard.vue
<template>
  <div class="tour-card m-3 shadow-md rounded-xl">
   <NuxtLink :to="`/${tour}`">
    <div class="p-5">
      <img :src="logo" :alt="tour">
    </div>
   </NuxtLink>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'

export default defineComponent({
  setup () {
    

    return {}
  },
  props: {
    logo: {
      type: String,
      required: true,
    },
    tour: {
      type: String,
      required: true,
    }
  }
})
</script>

<style scoped>
img {
  max-height: 300px;
}
</style>

// src/components/TourCard.tsx
import { Link } from 'react-router-dom';

const TourCard = ({ logo, tour }: { logo: string; tour: string }) => {
  return (
    <div className="tour-card m-3 shadow-md rounded-xl">
      <Link to={`/${tour}`}>
        <img
          className="tour-logo"
          src={logo}
          alt={`Logo of ${tour} tour`}
        />
      </Link>
    </div>
  );
};

export default TourCard;
